---
kind: pipeline
name: docker build/push
type: docker

trigger:
  branch:
    - master

steps:
  - name: build and push docker
    image: plugins/docker
    settings:
      username: "austin1howard"
      password:
        from_secret: dockerhub_token
      repo: austin1howard/drone-plugin-deploy-gate
      tags:
        - latest
        - "1.0.0"
      squash: true